-- Auto-generated proof for circuit: add
-- Description: Addition of two field elements
-- Generated by zkEVM Circuit Verifier Prototype

-- Define the circuit function
def add_circuit (a : Nat b : Nat) : Nat :=
  a + b

-- Correctness theorem: the circuit computes what we expect
theorem add_correct (a : Nat b : Nat) :
  add_circuit a b = a + b := by
  rfl

-- Soundness property: output matches specification
theorem add_sound (a : Nat b : Nat c : Nat)
  (h : c = add_circuit a b) :
  c = a + b := by
  simp [add_circuit] at h
  exact h

-- Example computation
#eval add_circuit 5 3

-- Verification status
#check add_correct
#check add_sound
