-- Auto-generated proof for circuit: multiply
-- Description: Multiplication of two field elements
-- Generated by zkEVM Circuit Verifier Prototype

-- Define the circuit function
def multiply_circuit (a : Nat b : Nat) : Nat :=
  a * b

-- Correctness theorem: the circuit computes what we expect
theorem multiply_correct (a : Nat b : Nat) :
  multiply_circuit a b = a * b := by
  rfl

-- Soundness property: output matches specification
theorem multiply_sound (a : Nat b : Nat c : Nat)
  (h : c = multiply_circuit a b) :
  c = a * b := by
  simp [multiply_circuit] at h
  exact h

-- Example computation
#eval multiply_circuit 5 3

-- Verification status
#check multiply_correct
#check multiply_sound
